# Generated by Django 3.1.1 on 2020-09-20 17:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20200920_1816'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Giftcard',
        ),
    ]
