# Generated by Django 3.1.1 on 2020-09-28 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_usersubscriptions_s_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersubscriptions',
            name='s_id',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
