# Generated by Django 3.1.1 on 2020-09-22 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_giftcards_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='giftcards',
            name='counter',
            field=models.IntegerField(default=0),
        ),
    ]
