# Generated by Django 3.1.1 on 2020-09-22 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_giftcards_counter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='giftcards',
            name='product',
        ),
        migrations.AddField(
            model_name='giftcards',
            name='product_id',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='giftcards',
            name='product_name',
            field=models.CharField(default='tennis_ball', max_length=50),
            preserve_default=False,
        ),
    ]
