# Generated by Django 3.1.1 on 2020-09-23 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_auto_20200923_1512'),
        ('users', '0007_auto_20200923_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcards',
            name='product_id',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
