# Generated by Django 3.1.1 on 2020-09-23 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200923_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftcards',
            name='product_id',
            field=models.IntegerField(),
        ),
    ]
