# Generated by Django 3.1.1 on 2020-09-27 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200926_2123'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='subscription',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='subscription_id',
            field=models.CharField(blank=True, default='', max_length=5000, null=True),
        ),
    ]
