# Generated by Django 3.1.1 on 2020-09-20 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='has_sizes',
            new_name='has_giftcard',
        ),
        migrations.RemoveField(
            model_name='product',
            name='rating',
        ),
    ]
