# Generated by Django 3.1.1 on 2020-09-23 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_auto_20200923_1435'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Type',
            new_name='Types',
        ),
        migrations.AlterModelOptions(
            name='types',
            options={'verbose_name_plural': 'Types'},
        ),
    ]
