# Generated by Django 3.1.1 on 2020-09-23 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_auto_20200923_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='what_type',
        ),
        migrations.DeleteModel(
            name='Types',
        ),
    ]
