# Generated by Django 3.1.1 on 2020-09-27 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0004_order_total'),
        ('products', '0006_auto_20200923_1512'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='ProductsStore',
        ),
    ]
